swagger: '2.0'
info:
  title: Receipt generator
  description: made by Yakubets Mykhailo
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: contact@snippets.local
  license:
    name: BSD License
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /add_new_order/:
    post:
      operationId: add_new_order_create
      description: Create checks for every printer at a point for every new order.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/AddNewOrder'
      responses:
        '201':
          description: 'Success response'
          schema:
            required:
              - result
            type: object
            properties:
              result:
                title: Result
                type: boolean
                example: true
        '400':
          description: 'Error response'
          schema:
            type: object
            properties:
              result:
                title: Result
                type: boolean
                example: false
                readOnly: true
              errors:
                title: Errors
                type: array
                readOnly: true
                items:
                  type: object
      tags:
        - add_new_order
    parameters: []
  /get_rendered_checks_at_point/{point}/:
    get:
      operationId: get_rendered_checks_at_point_read
      description: |-
        Get all Checks that are ready to be
        printed at a point with status changing.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/RenderedChecks'
      tags:
        - get_rendered_checks_at_point
    parameters:
      - name: point
        in: path
        required: true
        type: string
definitions:
  Product:
    required:
      - name
      - quantity
      - price
    type: object
    properties:
      name:
        title: Name
        type: string
        example: Hot Dog
        maxLength: 255
        minLength: 1
      quantity:
        title: Quantity
        type: integer
        minimum: 1
      price:
        title: Price
        type: integer
        example: 100
  AddNewOrder:
    required:
      - point_id
      - order_id
      - products
    type: object
    properties:
      point_id:
        title: Point id
        type: integer
        minimum: 0
      order_id:
        title: Order id
        type: integer
        example: 1111
        minimum: 1
      products:
        type: array
        items:
          $ref: '#/definitions/Product'
  RenderedChecks:
    required:
      - type
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      type:
        title: Check type
        type: string
        enum:
          - KITCHEN
          - CLIENT
      pdf_file:
        title: Link to the generated PDF file
        type: string
        example: 1111_KITCHEN.pdf
        readOnly: true
        x-nullable: true
        format: uri
