# Generated by Django 4.1.7 on 2023-03-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Printer name')),
                ('api_key', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Access key to API')),
                ('check_type', models.CharField(choices=[('KITCHEN', 'kitchen'), ('CLIENT', 'client')], max_length=7, verbose_name='Check type that the printer device prints')),
                ('point_id', models.PositiveSmallIntegerField(verbose_name='Point to which the printer is bound')),
            ],
            options={
                'db_table': 'printer',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KITCHEN', 'kitchen'), ('CLIENT', 'client')], max_length=7, verbose_name='Check type')),
                ('order', models.JSONField(verbose_name='Order information')),
                ('status', models.CharField(choices=[('NEW', 'new'), ('RENDERED', 'rendered'), ('PRINTED', 'printed')], default='NEW', max_length=8, verbose_name='Check status')),
                ('pdf_file', models.FileField(null=True, upload_to='media/pdf', verbose_name='Link to the generated PDF file')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.printer', verbose_name='Printer device')),
            ],
            options={
                'db_table': 'check',
            },
        ),
    ]
